version: '3'
services:
  postgres:
    image: postgres:11
    container_name: tender-hack-db
    environment:
      POSTGRES_USER: tender
      POSTGRES_PASSWORD: tender
      POSTGRES_DB: tender
    ports:
      - 5432:5432
